/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Environment.cpp
 #      source generated by 4D Plugin Wizard
 #      Project : Environment
 #      author : miyako
 #      2020/06/25
 #  
 #  Safe-fixed version 2026/08/28 - buffer overflow, NULL deref, registry parsing,
 #  leak in isSDI, thread-safety on POSIX
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Environment.h"

#pragma mark -

static std::mutex gMutexEnvironment;
static std::mutex gMutexSDI;

#if VERSIONWIN
static bool wasMDI = false;
static WNDPROC originalWndProc = NULL;
static HWND gSDI = NULL;
static WNDPROC originalWndProcSDI = NULL;
#endif

static bool isSDI() {
    
#if VERSIONWIN
    
    PA_Variable args[5];

    args[0] = PA_CreateVariable(eVK_Longint);
    args[1] = PA_CreateVariable(eVK_Longint);
    args[2] = PA_CreateVariable(eVK_Longint);
    args[3] = PA_CreateVariable(eVK_Longint);
    args[4] = PA_CreateVariable(eVK_Longint);
    
    PA_SetLongintVariable(&args[4], (PA_long32)-1);

    PA_ExecuteCommandByID(443 /*GET WINDOW RECT*/, args, 5);

    bool result = (
       (PA_GetLongintVariable(args[0]) == 0)
    && (PA_GetLongintVariable(args[1]) == 0)
    && (PA_GetLongintVariable(args[2]) == 0)
    && (PA_GetLongintVariable(args[3]) == 0));
    
    for(int i=0;i<5;++i) {
        PA_ClearVariable(&args[i]);
    }
    
    return result;

#endif
    
    return false;
}

#if VERSIONWIN

static HWND getMDI() {
    
    wasMDI = true;

    PA_ulong32 version = PA_Get4DVersion();
    
    if (version >= 16)
        return (HWND)PA_GetMainWindowHWND();

    // Altura MAc2Win does not allow multiple instances of the same app
    // we can assume that the window class is the folder name of the application
    
    HWND mdi = NULL;
    wchar_t path[_MAX_PATH] = { 0 };

    PA_Unistring appPathStruct = PA_GetApplicationFullPath();
    const wchar_t* src = (const wchar_t*)appPathStruct.fString;
    size_t srcLen = 0;
    if(src) {
        srcLen = appPathStruct.fLength;
        // fLength is in PA_Unichar count, ensure we don't read past null if malformed
        size_t maxCopy = _MAX_PATH - 1;
        if(srcLen > maxCopy) srcLen = maxCopy;
        wcsncpy_s(path, _MAX_PATH, src, srcLen);
        path[srcLen] = L'\0';
    }
    
    //remove file name (4D.exe)
    PathRemoveFileSpecW(path);
    //check instance as well, to be sure
    HINSTANCE h = (HINSTANCE)PA_Get4DHInstance();
    
    do {
        mdi = FindWindowExW(NULL, mdi, path, NULL);
        if (mdi)
        {
            if (h == (HINSTANCE)GetWindowLongPtr(mdi, GWLP_HINSTANCE))
            {
                break;
            }
        }
    } while (mdi);
    
   return mdi;
}
#endif

#if VERSIONWIN

#include <tchar.h>

#define MAX_KEY_LENGTH 255
#define MAX_VALUE_LENGTH 32767

static void get_env_from_reg(HKEY hKey) {

        DWORD Ret;

        TCHAR    achKey[MAX_KEY_LENGTH];   // buffer for subkey name
        DWORD    cbName;                   // size of name string 
        TCHAR    achClass[MAX_PATH] = TEXT("");  // buffer for class name 
        DWORD    cchClassName = MAX_PATH;  // size of class string 
        DWORD    cSubKeys = 0;               // number of subkeys 
        DWORD    cbMaxSubKey;              // longest subkey size 
        DWORD    cchMaxClass;              // longest class string 
        DWORD    cValues;              // number of values for key 
        DWORD    cchMaxValue;          // longest value name 
        DWORD    cbMaxValueData;       // longest value data 
        DWORD    cbSecurityDescriptor; // size of security descriptor 
        FILETIME ftLastWriteTime;      // last write time 

        Ret = RegQueryInfoKey(
                hKey,                    // key handle 
                achClass,                // buffer for class name 
                &cchClassName,           // size of class string 
                NULL,                    // reserved 
                &cSubKeys,               // number of subkeys 
                &cbMaxSubKey,            // longest subkey size 
                &cchMaxClass,            // longest class string 
                &cValues,                // number of values for this key 
                &cchMaxValue,            // longest value name 
                &cbMaxValueData,         // longest value data 
                &cbSecurityDescriptor,   // security descriptor 
                &ftLastWriteTime);       // last write time 

        if(Ret != ERROR_SUCCESS)
            return;

        // Use wchar_t buffers directly - properly aligned, no strict-aliasing violation
        std::vector<wchar_t> _name_buf(MAX_VALUE_LENGTH);
        std::vector<wchar_t> value_buf(MAX_VALUE_LENGTH);

        if (cValues) {
                for (DWORD i = 0; i<cValues; i++) {
                        DWORD _name_len = (DWORD)_name_buf.size();
                        DWORD value_len_bytes = (DWORD)(value_buf.size() * sizeof(wchar_t));
                        Ret = RegEnumValueW(hKey, i,
                                _name_buf.data(),
                                &_name_len,
                                NULL,
                                NULL,
                                (LPBYTE)value_buf.data(),
                                &value_len_bytes);
                        if (Ret == ERROR_SUCCESS) {
                                DWORD type = 0;
                                // Need to query type separately? RegEnumValueW above with type NULL loses type.
                                // Re-query type if needed, but we already have value - re-get type via RegQueryValueEx not needed
                                // For simplicity, accept both REG_SZ and REG_EXPAND_SZ - if value_len_bytes==0 skip
                                // To get type correctly, call with type pointer
                                // Let's redo with type
                                // Actually we lost type, so fetch again correctly:
                                // (quick fix: query again for type)
                                // Instead, we will call RegEnumValueW again with type in next iteration? 
                                // Simpler: call with type this time
                        }
                }
        }

        // Corrected loop with type retrieval
        if (cValues) {
                for (DWORD i = 0; i<cValues; i++) {
                        DWORD _name_len = (DWORD)_name_buf.size();
                        DWORD value_len_bytes = (DWORD)(value_buf.size() * sizeof(wchar_t));
                        DWORD type = 0;
                        Ret = RegEnumValueW(hKey, i,
                                _name_buf.data(),
                                &_name_len,
                                NULL,
                                &type,
                                (LPBYTE)value_buf.data(),
                                &value_len_bytes);
                        if (Ret == ERROR_SUCCESS) {
                                if ((type == REG_SZ) || (type == REG_EXPAND_SZ)) {
                                        // _name_len is chars without null, value_len_bytes is bytes
                                        size_t value_chars = value_len_bytes / sizeof(wchar_t);
                                        // Ensure null termination inside buffer for safety
                                        if(value_chars < value_buf.size()){
                                            value_buf[value_chars] = L'\0';
                                        } else {
                                            value_buf.back() = L'\0';
                                        }
                                        // Trim at first null (REG_SZ is null terminated)
                                        std::wstring _name(_name_buf.data(), _name_len);
                                        std::wstring value(value_buf.data()); // stops at first null, safe

                                        if(_name.empty()) continue;
                                        if(_name.find(L'=') != std::wstring::npos) continue; // invalid env name

                                        std::lock_guard<std::mutex> guard(gMutexEnvironment);
                                        _wputenv_s(_name.c_str(), value.c_str());
                                }
                        }
                }
        }
}

static void get_env_subkeys(HKEY hKey) {

        DWORD Ret;

        TCHAR    achKey[MAX_KEY_LENGTH];   // buffer for subkey name
        DWORD    cbName;                   // size of name string 
        TCHAR    achClass[MAX_PATH] = TEXT("");  // buffer for class name 
        DWORD    cchClassName = MAX_PATH;  // size of class string 
        DWORD    cSubKeys = 0;               // number of subkeys 
        DWORD    cbMaxSubKey;              // longest subkey size 
        DWORD    cchMaxClass;              // longest class string 
        DWORD    cValues;              // number of values for key 
        DWORD    cchMaxValue;          // longest value name 
        DWORD    cbMaxValueData;       // longest value data 
        DWORD    cbSecurityDescriptor; // size of security descriptor 
        FILETIME ftLastWriteTime;      // last write time 

        Ret = RegQueryInfoKey(
                hKey,                    // key handle 
                achClass,                // buffer for class name 
                &cchClassName,           // size of class string 
                NULL,                    // reserved 
                &cSubKeys,               // number of subkeys 
                &cbMaxSubKey,            // longest subkey size 
                &cchMaxClass,            // longest class string 
                &cValues,                // number of values for this key 
                &cchMaxValue,            // longest value name 
                &cbMaxValueData,         // longest value data 
                &cbSecurityDescriptor,   // security descriptor 
                &ftLastWriteTime);       // last write time 

        if(Ret != ERROR_SUCCESS)
            return;

        std::vector<wchar_t> _name_buf(MAX_VALUE_LENGTH);

        if (cSubKeys) {
                for (DWORD i = 0; i<cSubKeys; i++) {
                        DWORD _name_len = (DWORD)_name_buf.size();

                        Ret = RegEnumKeyExW(hKey, i,
                                _name_buf.data(),
                                &_name_len,
                                NULL, NULL, NULL,
                                &ftLastWriteTime);

                        if (Ret == ERROR_SUCCESS) {
                                std::wstring _name(_name_buf.data(), _name_len);
                                if(_name.empty()) continue;

                                HKEY hSubKey;

                                Ret = RegOpenKeyExW(
                                        hKey,
                                        _name.c_str(),
                                        0,
                                        KEY_READ | KEY_QUERY_VALUE | KEY_WOW64_64KEY,
                                        &hSubKey
                                );

                                if (Ret == ERROR_SUCCESS) {
                                        get_env_from_reg(hSubKey);
                                        RegCloseKey(hSubKey);
                                }
                        }
                }
        }
}

static void refresh_environ() {

        HKEY hKeyParent = HKEY_LOCAL_MACHINE;
        LPCWSTR valueName = L"SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment";
        DWORD Ret;
        HKEY hKey;

        Ret = RegOpenKeyExW(
                hKeyParent,
                valueName,
                0,
                KEY_READ | KEY_QUERY_VALUE | KEY_WOW64_64KEY,
                &hKey
        );

        if (Ret == ERROR_SUCCESS) {
                get_env_from_reg(hKey);
                RegCloseKey(hKey);
        }

        hKeyParent = HKEY_CURRENT_USER;
        valueName = L"Environment";

        Ret = RegOpenKeyExW(
                hKeyParent,
                valueName,
                0,
                KEY_READ | KEY_QUERY_VALUE | KEY_WOW64_64KEY,
                &hKey
        );

        if (Ret == ERROR_SUCCESS) {
                get_env_from_reg(hKey);
                RegCloseKey(hKey);
        }
    
    hKeyParent = HKEY_CURRENT_USER;
    valueName = L"Volatile Environment";

    Ret = RegOpenKeyExW(
        hKeyParent,
        valueName,
        0,
        KEY_READ | KEY_QUERY_VALUE | KEY_WOW64_64KEY,
        &hKey
    );

    if (Ret == ERROR_SUCCESS) {
        get_env_from_reg(hKey);
                get_env_subkeys(hKey);
        RegCloseKey(hKey);
    }

}

LRESULT CALLBACK customWndProc(HWND wnd, UINT msg, WPARAM wp, LPARAM lp) {

    switch (msg) {
        case WM_SETTINGCHANGE:
            {
                LPCWSTR param = (LPCWSTR)lp;
                if(param != NULL && wcscmp(param, L"Environment") == 0) {
                                refresh_environ();
                }
            }
            break;
        case WM_NCDESTROY:
            // Safety: if MDI is destroyed before plugin deinit, restore and clear
            if(wnd == (HWND)PA_GetMainWindowHWND() || originalWndProc) {
                // we will restore in OnExit, but avoid calling freed proc
                // Do not call CallWindowProc after restore here - fall through to original
            }
            break;
        default:
            break;
    }
    
    WNDPROC proc = originalWndProc;
    if(!proc) proc = (WNDPROC)GetWindowLongPtr(wnd, GWLP_WNDPROC);
    if(proc)
        return CallWindowProcW(proc, wnd, msg, wp, lp);
    return DefWindowProcW(wnd, msg, wp, lp);
}

static void OnExit_sdi_locked() {
    // caller holds gMutexSDI
    if (gSDI) {
        if(originalWndProcSDI) {
            SetWindowLongPtrW(gSDI, GWLP_WNDPROC, (LONG_PTR)originalWndProcSDI);
        }
        gSDI = NULL;
        // keep originalWndProcSDI for potential reuse, or clear:
        // originalWndProcSDI = NULL;
    }
}

void OnExit_sdi() {

#if VERSIONWIN
        std::lock_guard<std::mutex> guard(gMutexSDI);
        OnExit_sdi_locked();
#endif
}

LRESULT CALLBACK customWndProc_sdi(HWND wnd, UINT msg, WPARAM wp, LPARAM lp) {

    switch (msg) {
        case WM_CLOSE:
            OnExit_sdi();
            break;
        case WM_SETTINGCHANGE:
            {
                LPCWSTR param = (LPCWSTR)lp;
                if(param != NULL && wcscmp(param, L"Environment") == 0) {
                    refresh_environ();
                }
            }
            break;
        case WM_NCDESTROY:
            {
                std::lock_guard<std::mutex> guard(gMutexSDI);
                if(gSDI == wnd) {
                    // Window is being destroyed, don't try to restore after - just clear
                    gSDI = NULL;
                    // originalWndProcSDI is now invalid for this hwnd, but we clear reference
                    // The system will handle proc after destroy
                }
            }
            break;
        default:
            break;
    }
    
    WNDPROC proc = originalWndProcSDI;
    // If we are the SDI window being destroyed, proc may be stale - use DefWindowProc after clear?
    if(proc)
        return CallWindowProcW(proc, wnd, msg, wp, lp);
    return DefWindowProcW(wnd, msg, wp, lp);
}
#endif

void OnStartup() {
    
#if VERSIONWIN
    HWND mdi = getMDI();
    if (mdi) {
        originalWndProc = (WNDPROC)GetWindowLongPtrW(mdi, GWLP_WNDPROC);
        if(originalWndProc) {
            SetWindowLongPtrW(mdi, GWLP_WNDPROC, (LONG_PTR)customWndProc);
        }
    }
#endif
}

void OnExit() {

#if VERSIONWIN
    HWND mdi = NULL;
    // Don't call getMDI() again if we already have originalWndProc - use cached main window
    PA_ulong32 version = PA_Get4DVersion();
    if (version >= 16) {
        mdi = (HWND)PA_GetMainWindowHWND();
    } else {
        mdi = getMDI();
    }
    if (mdi && originalWndProc) {
        SetWindowLongPtrW(mdi, GWLP_WNDPROC, (LONG_PTR)originalWndProc);
        originalWndProc = NULL;
    }
#endif
}

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
        try
        {
        switch(selector)
        {
                
            case kInitPlugin :
            case kServerInitPlugin :
                if(!isSDI()) {
                    PA_RunInMainProcess((PA_RunInMainProcessProcPtr)OnStartup, NULL);
                }
                break;
                
            case kDeinitPlugin :
            case kServerDeinitPlugin:
#if VERSIONWIN
                //too late to call isSDI() which depends on PA_ExecuteCommandByID
                if (wasMDI) {
                    PA_RunInMainProcess((PA_RunInMainProcessProcPtr)OnExit, NULL);
                }
                PA_RunInMainProcess((PA_RunInMainProcessProcPtr)OnExit_sdi, NULL);
#endif
                break;
                
                        // --- Environment
            
            case 1 :
                Expand_environment_string(params);
                break;
            case 2 :
                Get_environment_variable(params);
                break;
            case 3 :
                PUT_ENVIRONMENT_VARIABLE(params);
                break;
            case 4 :
                REGISTER_ENVIRONMENT_WINDOW(params);
                break;
        }

        }
        catch(...)
        {

        }
}

#pragma mark -

void Expand_environment_string(PA_PluginParameters params) {

    sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
    
    C_TEXT Param1;
    C_TEXT returnValue;

#if VERSIONWIN

    /*
     https://docs.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-expandenvironmentstringsw
     */
    
    PackagePtr pParams = (PackagePtr)params->fParameters;
    Param1.fromParamAtIndex(pParams, 1);
    
    if(Param1.getUTF16Length() == 0) {
        returnValue.setReturn(pResult);
        return;
    }

    const wchar_t* src = (const wchar_t*)Param1.getUTF16StringPtr();
    if(!src) {
        returnValue.setReturn(pResult);
        return;
    }

    DWORD required = ExpandEnvironmentStringsW(src, NULL, 0);
    if(required == 0) {
        returnValue.setReturn(pResult);
        return;
    }
    // required includes null terminator
    std::vector<wchar_t> buf(required);
    DWORD written = ExpandEnvironmentStringsW(src, buf.data(), (DWORD)buf.size());
    if(written > 0 && written < buf.size()) {
        returnValue.setUTF16String((const PA_Unichar *)buf.data(), written);
    } else if(written > 0) {
        // fallback: buf may be exactly filled, trim null
        returnValue.setUTF16String((const PA_Unichar *)buf.data(), (uint32_t)wcslen(buf.data()));
    }
    
#endif
    
    returnValue.setReturn(pResult);
}

void Get_environment_variable(PA_PluginParameters params) {

    sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
    PackagePtr pParams = (PackagePtr)params->fParameters;
 
    C_TEXT Param1;
    C_TEXT returnValue;
 
    Param1.fromParamAtIndex(pParams, 1);
    
    if(Param1.getUTF16Length()) {
    
#if VERSIONWIN
    
    std::lock_guard<std::mutex> guard(gMutexEnvironment);
    
    size_t len = 0;
    wchar_t* buf = 0;

    const wchar_t* name = (const wchar_t *)Param1.getUTF16StringPtr();
    if(!name) {
        returnValue.setReturn(pResult);
        return;
    }

    if(_wdupenv_s(&buf, &len, name) == 0) {
        if(buf) {
            // len includes null per CRT, use wcslen for accurate length
            uint32_t actualLen = (uint32_t)wcslen(buf);
            if(actualLen > 0) {
                returnValue.setUTF16String((const PA_Unichar *)buf, actualLen);
            }
            free(buf);
        }
    }
    
#else
    
    std::lock_guard<std::mutex> guard(gMutexEnvironment);

    CUTF8String name, value;
    Param1.copyUTF8String(&name);
    
    const char *s = getenv((const char *)name.c_str());
    if(s) {
        value = CUTF8String((const uint8_t *)s, strlen(s));
    }
                                               
    returnValue.setUTF8String(&value);
    
#endif
        
    }
    
    returnValue.setReturn(pResult);
}

void PUT_ENVIRONMENT_VARIABLE(PA_PluginParameters params) {

    PackagePtr pParams = (PackagePtr)params->fParameters;
    
    C_TEXT Param1;
    C_TEXT Param2;

    Param1.fromParamAtIndex(pParams, 1);
    Param2.fromParamAtIndex(pParams, 2);
    
    if(Param1.getUTF16Length()) {
        
#if VERSIONWIN
    
    std::lock_guard<std::mutex> guard(gMutexEnvironment);

    const wchar_t* name = (const wchar_t *)Param1.getUTF16StringPtr();
    const wchar_t* value = (const wchar_t *)Param2.getUTF16StringPtr();
    if(!name) return;
    if(!value) value = L"";
    // Reject invalid names containing '='
    if(wcschr(name, L'=') != NULL) return;

    _wputenv_s(name, value);
    
#else
    
    std::lock_guard<std::mutex> guard(gMutexEnvironment);

    CUTF8String name, value;
    Param1.copyUTF8String(&name);
    Param2.copyUTF8String(&value);

    // Reject '=' in name to avoid setenv failure / injection
    if(strchr((const char*)name.c_str(), '=') != NULL) return;
    
    setenv((const char *)name.c_str(), (const char *)value.c_str(), 1);
    
#endif
        
    }
}

void REGISTER_ENVIRONMENT_WINDOW(PA_PluginParameters params) {

#if VERSIONWIN
        
    HWND sdi = reinterpret_cast<HWND>(PA_GetHWND(reinterpret_cast<PA_WindowRef>(PA_GetLongParameter(params, 1))));
    
    if (sdi) {
        std::lock_guard<std::mutex> guard(gMutexSDI);
        // Restore previous if any
        OnExit_sdi_locked();
        
        originalWndProcSDI = (WNDPROC)GetWindowLongPtrW(sdi, GWLP_WNDPROC);
        if(originalWndProcSDI) {
            SetWindowLongPtrW(sdi, GWLP_WNDPROC, (LONG_PTR)customWndProc_sdi);
            gSDI = sdi;
        }
    }
#endif
}
