/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Environment.h
 #	source generated by 4D Plugin Wizard
 #	Project : Environment
 #	author : miyako
 #	2020/06/25
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ENVIRONMENT_H
#define PLUGIN_ENVIRONMENT_H

#include "4DPluginAPI.h"

#include <mutex>
#if VERSIONWIN
#include "shlwapi.h"
#endif
#include "C_TEXT.h"

#pragma mark -

void Expand_environment_string(PA_PluginParameters params);
void Get_environment_variable(PA_PluginParameters params);
void PUT_ENVIRONMENT_VARIABLE(PA_PluginParameters params);

#endif /* PLUGIN_ENVIRONMENT_H */
