/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Environment.h
 #	source generated by 4D Plugin Wizard
 #	Project : Environment
 #	author : miyako
 #	2020/06/25
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ENVIRONMENT_H
#define PLUGIN_ENVIRONMENT_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"

#pragma mark -

static void Expand_environment_string(PA_PluginParameters params);
static void Get_environment_variable(PA_PluginParameters params);
static void PUT_ENVIRONMENT_VARIABLE(PA_PluginParameters params);
static void REGISTER_ENVIRONMENT_WINDOW(PA_PluginParameters params);

#endif /* PLUGIN_ENVIRONMENT_H */
